### ISSUE TITLE
Can we open a wiki?

### ISSUE THREAD

**Issue by zoutepopcorn** [cnlohr/espusb#16]
Some people don't know howto install things. Can we open the wiki, so we can document things together?

Thanks for sharing the USP8266 :D.

**Comment by cnlohr** [comment]
How does that work?  I've never done any such thing.  Can it be done with github?  Where would I set it up. The answer to this is a resounding YES!  Anything that can get more people into this is a BIG PLUS for me.  I just don't know what I'm doing!

**Comment by cnlohr** [comment]
Hey! I found the button.  I just created it.  I would be up for working on it more later. Do you know if you have to be a contributor to edit it?

**Comment by leopck** [comment]
I think anyone else can contribute by forking espusb then merging back. Probably there's other ways to do it?

**Comment by cnlohr** [comment]
I just found a checkbox and unchecked it.  See if you can edit it now.

**Comment by leopck** [comment]
Yeah, seem that we can edit now. I'm not sure if this is good since it means that anyone can change the content.

**Comment by cnlohr** [comment]
Yay! I see the edit.  If someone else wouldn't mind starting to fill it out, I can edit more tomorrow.  I'm already in a documentation mode, so I'll already be writing.

Re: Who can edit:  I get two options "Collaborators ONLY" or "Anyone on Github" and I'm leaning toward the second, until it becomes an issue.

**Comment by leopck** [comment]
I can help fill up on how to get started guide for users that are interested in using the espusb, make, make burn and the website.

"Anyone on Github" that sounds great, I guess you could try it out first and if there's no issue then it's fine probably? Hopefully no one tries to play pranks and delete the whole wiki that everyone would be creating...

**Comment by leopck** [comment]
@cnlohr I'm just filling in basic things that I know of, if there's any mistakes just edit them away or if the format of the wiki isn't nice then just re-format it :)

**Comment by zoutepopcorn** [comment]
Nice. Welk doen :)
