### ISSUE TITLE
Error: unknown opcode or format name 'ss'

### ISSUE THREAD

**Issue by leopck** [cnlohr/espusb#2]
Hi, I was compiling, and I got this error
"Error: unknown opcode or format name 'ss'"
I noticed in your latest commit for "user/usb_asm_1bit.S" on line 419 there's a new instruction?

419     +ss	//http://www.ti.com/lit/an/spraat5a/spraat5a.pdf 7.1.9

I removed it and I could compile again. Is the "ss" a typo?

**Comment by cnlohr** [comment]
Yes! Actually I will be committing a new copy later today that adds comments, too!  Sorry!

**Comment by cnlohr** [comment]
fixed in fc108fb
