### ISSUE TITLE
Profiling for esp8266 based code

### ISSUE THREAD

**Issue by yadavravi079** [cnlohr/espusb#35]
Basic Infos
Hardware

Hardware: ESP8266
Core Version:
Description

Hi guys! I have developed a project based on NodeMCU, Now I am trying to debugging and profiling it.
Can any could please help how to profile the code?
I am able to debug it using gdb over eclipse and now I am trying to compile it using -pg Flag so that it gnenerate some info using mcount() and then I could use Gprof for further profiling.
Share some ideas would be appreciated.
Settings in IDE

Module: NodeMCU
Flash Size: 4MB
CPU Frequency: 80Mhz
Flash Mode: dio
Flash Frequency: 40Mhz
Upload Using: SERIAL
Reset Method: nodemcu

**Comment by cnlohr** [comment]
I really don't know what to suggest for that.  I definitely don't work in that environment and it's not really the place for ESPUSB.  I recommend moving this to http://github.com/cnlohr/esp82xx if you really want.
