### ISSUE TITLE
Nodemcu with espusb

### ISSUE THREAD

**Issue by openscoreboard** [cnlohr/espusb#40]
I have a nodemcu
I can flash espusb inside
I can connect my smartphone to 192.168.4.1
But i lost connection if push web buttons...

What schematic need for connect a nodemcu and work with espusb in mode hid?

Thank!!!

**Comment by cnlohr** [comment]
Please see schematic info on this page: https://github.com/cnlohr/espusb

Charles

**Comment by openscoreboard** [comment]
I try flash to 0x100000 but the connection from smartphone lost again....
I see schematic too, but my nodemcu is a little diferent...

Is It ok my connection?

![example](https://user-images.githubusercontent.com/17176206/36497368-7c2157b0-173b-11e8-9cfc-24dde9e80b9d.png)

Thanks...

**Comment by cnlohr** [comment]
What resistor are you using?  1.5k is nominal.   Connection should be ok.

Do you have access to a Linux computer, using ```dmesg``` it can make it much easier to understand what's going on.

**Comment by openscoreboard** [comment]
I have a resistor with 1,2K  

And this is the output dmesg

> [sáb mar  3 13:23:35 2018] ch341 2-2:1.0: device disconnected
[sáb mar  3 13:23:40 2018] usb 2-2: new full-speed USB device number 5 using uhci_hcd
[sáb mar  3 13:23:40 2018] usb 2-2: New USB device found, idVendor=1a86, idProduct=7523
[sáb mar  3 13:23:40 2018] usb 2-2: New USB device strings: Mfr=0, Product=2, SerialNumber=0
[sáb mar  3 13:23:40 2018] usb 2-2: Product: USB2.0-Serial
[sáb mar  3 13:23:40 2018] ch341 2-2:1.0: ch341-uart converter detected
[sáb mar  3 13:23:40 2018] usb 2-2: ch341-uart converter now attached to ttyUSB0

> 
My steps

- Connect NODEMCU by USB to PC (linux)
- run commands make burn and make burnweb (my nodemcu blink the  led)
-Disconnect USB
-Connect GPIO4+resistor+3v
-Reconnect USB to PC
-I think that no happend nothing 

Thanks...

**Comment by cnlohr** [comment]
uuhhhh ... can you take a picture of your setup?  I don't see where you're hooking the second USB in.  Also, you should never need to unplug the NodeMCU usb. Just plug both USB plugs in.

**Comment by openscoreboard** [comment]
I have only one USB port connect to my PC.
This is my connection
![image](https://user-images.githubusercontent.com/17176206/36938778-27b55afc-1f27-11e8-9119-78c4e16ff6f7.png)

**Comment by openscoreboard** [comment]
oooohhhh!!!
I think I understood it now.
It is necessary to connect a second USB to the GPIO5 (D +) and GPIO4 (D-) pin.
This second USB is the works as HID
Is correct?

**Comment by cnlohr** [comment]
YES

**Comment by openscoreboard** [comment]
Now this is my setup

![seleccion_014](https://user-images.githubusercontent.com/17176206/36949157-cab3b09c-1fe4-11e8-9fe8-57579be33fa7.png)

One USB for flash and other for HID


This is my dmesg now...


> [  263.532501] ch341 3-1:1.0: device disconnected
[  270.544035] usb 3-1: new full-speed USB device number 4 using uhci_hcd
[  270.719080] usb 3-1: New USB device found, idVendor=1a86, idProduct=7523
[  270.719085] usb 3-1: New USB device strings: Mfr=0, Product=2, SerialNumber=0
[  270.719089] usb 3-1: Product: USB2.0-Serial
[  270.721268] ch341 3-1:1.0: ch341-uart converter detected
[  270.728196] usb 3-1: ch341-uart converter now attached to ttyUSB0
[  280.808041] usb 5-2: new full-speed USB device number 14 using uhci_hcd
[  281.148045] usb 5-2: device descriptor read/64, error -71
[  281.384144] usb 5-2: device descriptor read/64, error -71
[  281.612035] usb 5-2: new full-speed USB device number 15 using uhci_hcd
[  281.740030] usb 5-2: device descriptor read/64, error -71
[  281.976033] usb 5-2: device descriptor read/64, error -71
[  282.204032] usb 5-2: new full-speed USB device number 16 using uhci_hcd
[  282.620032] usb 5-2: device not accepting address 16, error -71
[  282.740030] usb 5-2: new full-speed USB device number 17 using uhci_hcd
[  283.156030] usb 5-2: device not accepting address 17, error -71
[  283.156061] usb usb5-port2: unable to enumerate USB device

>

**Comment by cnlohr** [comment]
It is likely you've either flipped the D+/D- pins or some issue with the pullup resistor being large enough, etc.

**Comment by openscoreboard** [comment]
The last week i tried connect one wemos d1 and dont work for me.

I think that my firmware isnt ok.
Is there a link to donwload the firmware pre-compiled?

Thanks

**Comment by joBr99** [comment]
In this repository is a pre compiled firmware. You can flash it with the esptool and the following command:
esptool.py -b 115200 --port /dev/ttyUSB0 write_flash 65536 web/page.mpfs

As I have already said it does not work for me, I will attach my compiled firmware too.

[page.mpfs.zip](https://github.com/cnlohr/espusb/files/1865763/page.mpfs.zip)

**Comment by cnlohr** [comment]
The page.mpfs is only the webpage... you'll need both the 0x0000 and 0x4000 binaries.  I don't have them handy, sadly.

**Comment by joBr99** [comment]
Thanks, I overlooked that ... now it is working.

**Comment by cnlohr** [comment]
@joBr99 Would you mind uploading your binaries?

**Comment by cnlohr** [comment]
Thank you!

**Comment by cnlohr** [comment]
I am posting this thread to the main readme.

**Comment by ntinos97** [comment]
> esptool.py -b 115200 --port /dev/ttyUSB0 write_flash -fm dio 0x00000 image.elf-0x00000.bin 0x40000 image.elf-0x40000.bin
> esptool.py -b 115200 --port /dev/ttyUSB0 write_flash 65536 web/page.mpfs
> 
> [espusb.zip](https://github.com/cnlohr/espusb/files/1866448/espusb.zip)

love you...i had all day until to find this solution... thank you so much

**Comment by NicoAlmazan** [comment]
Hello guys.. I think I f*** it up. Today I boght this Module I share with you in the picture. 
![image](https://user-images.githubusercontent.com/98363775/150883907-c551099b-fae0-444f-b1ad-5e4a155d1421.png)

I tryed to make it work but I couldn´t. I even flashed it on the memory addresses you shared. image.elf-0x00000.bin 0x40000 image.elf-0x40000.bin and web/page.mpfs to 0x100000
It kindda work.. but it is not the interface I am used to see on videos and it does not even send commands to the module.
This is what everybody sees:

![image](https://user-images.githubusercontent.com/98363775/150884318-a8742eb5-18a3-4602-858a-1ee8203f7f1a.png)

This is what I see:

![image](https://user-images.githubusercontent.com/98363775/150885378-cf05a41c-dc2a-4442-beda-7a251b57cf9b.png)


Can you guys please help me? 
Thank you
