### ISSUE TITLE
Need Help at Antenna Designing

### ISSUE THREAD

**Issue by shinkuan** [cnlohr/espusb#67]
So I'm trying to design my own ESPUSB as well, but when it comes to antenna designing, I have no clue what do I do.
I've searched and found the datasheet of the antenna that example board used. [[Link]](https://datasheet.lcsc.com/lcsc/1808272258_Walsin-Tech-Corp-RFECA3216060A1T_C127620.pdf)
And from the datasheet, the datasheet recommended design looks far from the [usb_8285](https://github.com/cnlohr/espusb/tree/master/hardware/usb_8285) in this repository.
![Image of the design](https://user-images.githubusercontent.com/35415788/175012650-72b2d4db-2b54-409f-af65-8da7819b4532.jpg)
Above is the design in the repository. The green part is the ceramic antenna. And I think the cyan part is some sort of antenna design? which I have no idea what it is.
I want my board to be as small as the one in this repository or even smaller, so anyone have idea how to do it?

**Comment by shinkuan** [comment]
Or some design look like this is ok either. I just don't know how to do it.
![esp-10-wifi-module-with-esp8266-without-antenna](https://user-images.githubusercontent.com/35415788/175017435-f6a85c44-31a7-4fc8-9992-d671570064f1.jpg)

**Comment by cnlohr** [comment]
Honestly,
![image](https://user-images.githubusercontent.com/2748168/200953996-bda5c37f-08b8-401e-857c-3a22f96a2d0b.png)
And so far, it hasn't been an issue.
