### ISSUE TITLE
are there any files that have been binned

### ISSUE THREAD

**Issue by adi160885** [cnlohr/espusb#75]
I always fail to install esp-open-sdk with components that always have errors including the supporting links
I ask for permission from you, can you provide a ready-made "firmware file bin" to flash easily, we would be very grateful if you provide for that, thank you in advance

**Comment by adi160885** [comment]
sorry, I didn't read everything, apparently there is already a binary that already provides it.
Thank You
https://github.com/cnlohr/espusb/issues/40#issuecomment-377770936

**Comment by cnlohr** [comment]
Can I close the ticket?
